[mutmut]
paths_to_mutate = "apps/"

exclude_patterns = [
    "*/migrations/*",
    "*/tests/*",
    "**/test_*.py",
    "*/admin.py",
    "*/apps.py",
    "*/conftest.py",
    "*/management/commands/*",
]

runner = "python -m pytest --no-cov -x --tb=short"

dict_synonyms = "Struct,NamedStruct"
